Creating arrays

In [2]:
import numpy as np

In [4]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [6]:
np.array([[16, 17, 18], [19, 20, 21]])

array([[16, 17, 18],
       [19, 20, 21]])

In [7]:
arr1 = np.array([1, 2, 3, 4, 5])

Sum

In [8]:
sum_arr1 = np.sum(arr1)

In [9]:
print (sum_arr1)

15


Mean

In [11]:
arr2 = np.array([[6, 7, 8], [9, 10, 11]])

In [12]:
mean_arr2 = np.mean(arr2)

In [13]:
print (mean_arr2)

8.5


Element_wise

In [14]:
element_wise_product = arr1 * arr1

In [15]:
print(element_wise_product)

[ 1  4  9 16 25]


Indexing and slicing

In [16]:
element_3 = arr1[2] # third element of arr1
row_1 = arr2[0] # first row of arr2
col_2 = arr2[:, 1] # second column of arr2

In [17]:
print("Third element", element_3)
print("First row:", row_1)
print("Second column", col_2)

Third element 3
First row: [6 7 8]
Second column [ 7 10]
